manifest_path: "/home/linux_subsys/PycharmProjects/q2-pan-classifier/q2_pan_classifier/scripts/script_test_dir/CoronaVirus/manifest"
metadata_path: "/home/linux_subsys/PycharmProjects/q2-pan-classifier/q2_pan_classifier/scripts/script_test_dir/CoronaVirus/bat_cov_metadata.tsv"
classifier_path: "/home/linux_subsys/PycharmProjects/q2-pan-classifier/q2_pan_classifier/scripts/script_test_dir/CoronaVirus/classifier/classifier.qza"
query_string: "Picornaviridae[ORGANISM] AND 5000:10000000[SLEN]"
forward_primer: "CAAGCACTTCTGTTTCCCCGG"
reverse_primer: "ATTGTCACCATAAGCAGCCA"
min_length: "0"
max_length: "500"
trunc_len_f: "200"
trunc_len_r: "200"